service/grails-app/domain/feedfacade/SourceFeed.groovy
package feedfacade

class SourceFeed {

  // The "Code" by which this feed will be known - Used for the front end feed url
  String uriname

  // Status - 'in-process', 'paused'  -- in-process if being actively checked
  String status 

  // CAP Community evaluation -- unusable, operating, testing
  String capAlertFeedStatus

  String name

  // Base URL of the underlying feed which will be polled
  String baseUrl 

  // The last time the status changed TO in-process
  Long lastStarted

  // The time the feed last changed from 'in-process' to 'paused'
  Long lastCompleted

  // The time the feed went from 'paused' to 'in-process'
  Long processingStartTime 

  // How long to wait between polls
  Long pollInterval

  // Highest timestamp seen on any entry
  Long highestTimestamp

  // Time taken to process feed on last run
  Long lastElapsed

  // Number of consecutive errors for retry
  Long consecutiveErrors

  String feedStatus

  String lastError

  String httpExpires

  String httpLastModified

  boolean enabled = false;

  Long latestHealth = 0

  String feedBrandingUrl

  static hasMany = [
    topics:FeedTopic,
    feedIssues:FeedIssue
  ]

  static mappedBy = [
    topics:'ownerFeed',
    feedIssues:'ownerFeed'
  ]

  // Last hash
  String lastHash

  static constraints = {
              lastHash blank: false, nullable:true
                  name blank: false, nullable:true
      highestTimestamp nullable:true
            feedStatus blank: false, nullable:true
             lastError nullable:true
           lastElapsed nullable:true
    capAlertFeedStatus blank: false, nullable:true
           httpExpires blank: false, nullable:true
      httpLastModified blank: false, nullable:true
     consecutiveErrors nullable:true
         lastCompleted nullable:true
	   lastStarted nullable:true
          latestHealth nullable:true
       feedBrandingUrl nullable:true
  }

  static mapping = {
    baseUrl index:'baseUrl_Idx,pendingChecksIdx'
    enabled index:'checkerIdx,pendingChecksIdx'
    feedStatus index:'checkerIdx'
    lastCompleted index:'checkerIdx,pendingChecksIdx'
    lastError type:'text'
    name index:'name_Idx'
    status index:'status_Idx,pendingChecksIdx'
    topics sort:'topic'
    uriname index:'uriname_Idx'
  }

  public void addTopics(String topicList) {
    def topics = topicList.split(',');
    SourceFeed.withTransaction {
      topics.each { raw_topic ->
        def normalised_topic = raw_topic.trim().toLowerCase()
        if ( normalised_topic.length() > 0 ) {
          log.debug("    Adding topic ${normalised_topic} to feed ${this.id}");
          def topic = Topic.findByName(normalised_topic) ?: new Topic(name:normalised_topic).save(flush:true, failOnError:true);
          def feed_topic = FeedTopic.findByOwnerFeedAndTopic(this, topic) ?: new FeedTopic(ownerFeed:this, topic:topic).save(flush:true, failOnError:true);
        }
      }
    }
  }

  def getHistogram() {
    SourceFeedStats.executeQuery('select sfs from SourceFeedStats as sfs where sfs.owner = :owner order by sfs.lastUpdate asc',[ owner:this]);
  }

  def getHistogramLastDay() {
    def start_time = System.currentTimeMillis() - ( 25 * 60 * 60 * 1000 ) 
    SourceFeedStats.executeQuery('select sfs from SourceFeedStats as sfs where sfs.owner = :owner and sfs.lastUpdate > :start_time order by sfs.lastUpdate asc', [ owner:this, start_time : start_time ]);
  }

  def addTag(tag_txt,value) {
    if ( value && 
         ( value.trim().length() > 0 ) &&
         ( !value.toString().equals('null') ) ) {
      def tag = Tag.findByTag(tag_txt) ?: new Tag(tag:tag_txt).save(flush:true, failOnError:true);
      def source_tag = SourceTag.findByOwnerAndTagAndValue(this,tag,value) ?: new SourceTag(owner:this, tag:tag, value:value).save(flush:true, failOnError:true);
    }
  }

  def getTags() {
    SourceTag.findAllByOwner(this)
  }

  def findTagValues(String tag) {
    return SourceTag.findAllByOwnerAndTag(this,tag)
  }

  public boolean isTagged(String tag, String value) {
    int num_rows = SourceTag.executeQuery('select count(*) from SourceTag as st where st.owner = :owner and st.tag.tag = :tag and st.value = :value',
                                          [owner:this, tag:tag, value:value]).get(0);
    return ( num_rows > 0 )
  }

  def getTimeToNextPoll() {
    return getNextPollTime() - System.currentTimeMillis()
  }

  def getNextPollTime() {
    lastCompleted + pollInterval
  }

  public static staticRegisterFeedIssue(Long id, String key, String message) {
   try {
      SourceFeed.withNewTransaction {
        def issue = null;
        def issues = FeedIssue.executeQuery('select fi from FeedIssue as fi where fi.ownerFeed.id = :o and fi.key=:key',[o:id, key:key])
        switch ( issues?.size() ) {
          case 0:
            issue = new FeedIssue(ownerFeed:SourceFeed.get(id),
                                  key:key,
                                  message:message,
                                  firstSeen:System.currentTimeMillis(),
                                  occurrences:0);
            break;
          case 1:
            issue = issues[0]
            break;
          default:
            throw new RuntimeException("Too many issues for this feed with this key");
        }

        issue.lastSeen = System.currentTimeMillis()
        issue.occurrences++;
        issue.save(flush:true, failOnError:true);
      }
    }
    catch ( Exception e ) {
      e.printStackTrace()
    }
  }

  public registerFeedIssue(String key, String message) {
    try {
      if ( ( key != null ) &&
           ( message != null ) ) {

        if ( key.length() > 254 )
          log.warn("Unexpectedly long key for feed issue: ${key}");

        if ( message.length() > 254 )
          log.warn("Unexpectedly long message for feed issue: ${message}");

        SourceFeed.withTransaction {
          log.debug("${this.uriname} registerFeedIssue(${key},${message})");
  
          String trunc_key = key.take(254);
          def issue = FeedIssue.findByOwnerFeedAndKey(this, trunc_key)
    
          if ( issue == null ) {
            issue = new FeedIssue(ownerFeed:this, key:trunc_key, message:message?.take(254), firstSeen:System.currentTimeMillis(), occurrences:0);
          }
  
          issue.lastSeen = System.currentTimeMillis()
          issue.occurrences++;
          issue.save(flush:true, failOnError:true);
        }
      }
    }
    catch ( Exception e ) {
      e.printStackTrace()
    }
  }

  private List<FeedIssue>latestIssues(int max) {
    List<FeedIssue> r = FeedIssue.executeQuery('select fi from FeedIssue as fi where fi.ownerFeed=:o order by lastSeen desc',[o:this],[max:max]);
    return r
  }

  public List<FlagEvent> getFlags() {
    List<FlagEvent> result = null;
    if ( this.id != null ) {
      result = FlagEvent.executeQuery('select fe from FlagEvent fe where fe.resourceType=:rt and fe.resourceId=:id',
                                      [rt:'feedfacade.SourceFeed', id:this.id.toString()]);
    }
    return result;
  }
}

service/grails-app/controllers/feedfacade/SourcefeedController.groovy
package feedfacade

import grails.plugin.springsecurity.annotation.Secured
import grails.converters.*



class SourcefeedController {

  // Up max time to 2 minutes - not ideal, but we've seen feeds take 60s sometimes
  private static int MAX_TIME_FOR_PROCESSING=120000;

  def index() { 
    long start_time = System.currentTimeMillis();

    def pagination_props = [ 
         max: params.max ?: 10,  
      offset: params.offset ?: 0 
    ]

    log.debug("SourcefeedController::index ${pagination_props}");
    def result = [:]

    def qry_params = [:]
    def base_feed_qry = ' from SourceFeed as sf'
    int clause_count = 0;
    // def order_by_clause = ' order by (sf.lastCompleted + sf.pollInterval)'
    if ( ( params.q != null ) && ( params.q.length() > 0 ) ) {
      base_feed_qry += ' where ( lower(sf.uriname) like :a or lower(sf.name) like :a or lower(baseUrl) like :a ) '
      qry_params.a = "%${params.q.toLowerCase()}%".toString()
      clause_count++;
    }
    def order_by_clause = ' order by sf.id'

    if ( params.filterHasErrors=='on' ) {

      if ( clause_count == 0 )
        base_feed_qry += ' where '
      else 
        base_feed_qry += ' and '

      base_feed_qry += 'exists ( select sfs.owner from SourceFeedStats as sfs where sfs.owner = sf and sfs.lastUpdate > :start_time group by sfs.owner having sum(sfs.errorCount) > 0 )'
      qry_params.start_time = System.currentTimeMillis() - ( 25 * 60 * 60 * 1000 )
      clause_count++;
    }

    if ( params.filterEnabled=='on' ) {
      if ( clause_count == 0 ) base_feed_qry += ' where ' else base_feed_qry += ' and '

      base_feed_qry += 'sf.enabled = :true'
      qry_params.true = true
      clause_count++;
    }

    if ( params.filterInProcess == 'on' ) {
      if ( clause_count == 0 ) base_feed_qry += ' where ' else base_feed_qry += ' and '
      base_feed_qry += 'sf.status = :inprocess'
      qry_params.inprocess = 'in-process'
      clause_count++;
    }

    log.debug("About to count blocked feeds - elasped - ${System.currentTimeMillis() - start_time}");
    // Count how many feeds might be blocked
    result.blocked_feeds = SourceFeed.executeQuery('select count(sf) from SourceFeed as sf where sf.status=:inProcess and sf.lastStarted < :blocktime', 
                                                   [blocktime:System.currentTimeMillis()-MAX_TIME_FOR_PROCESSING, inProcess:'in-process'])[0];


    log.debug("About to count feeds - elasped - ${System.currentTimeMillis() - start_time}");
    result.totalFeeds = SourceFeed.executeQuery('select count(sf) '+base_feed_qry,qry_params)[0]

    log.debug("About to find feeds - elasped - ${System.currentTimeMillis() - start_time}");
    result.feeds = SourceFeed.executeQuery('select sf '+base_feed_qry+order_by_clause,qry_params,pagination_props)

    log.debug("found ${result.totalFeeds} feeds - elasped - ${System.currentTimeMillis() - start_time}");

    result
  }

  @Secured(['ROLE_USER', 'IS_AUTHENTICATED_FULLY'])
  def registerFeed() {
    log.debug("SourcefeedController::registerFeed");
    def result = [:]

    try {

      log.debug("Checking ${request.method}");

      if ( request.method=='POST' ) {

        log.debug("Checking post contains a uriname: ${params}");

        if ( ( params.feedname ) && ( params.feedname.trim().length() > 0 ) ) {

          SourceFeed.withTransaction {

            log.debug("Find by Uriname ${params.feedname}");

            def feed = SourceFeed.findByUriname(params.feedname)

            if ( feed == null ) {
              log.debug("Create new feed ${params}");
              feed = new SourceFeed(uriname:params.feedname, baseUrl:params.baseUrl, pollInterval:params.pollInterval, status:'paused', processingStartTime:0, lastCompleted:0).save(flush:true, failOnError:true);
              feed.addTopics(params.topics)
            }
            else {
              log.debug("Update feed ${params}");
              feed.pollInterval = params.pollInterval
              feed.baseUrl=params.baseUrl
              feed.save(flush:true, failOnError:true)
            }
          }
        }
      }
    }
    catch ( Exception e ) {
      log.error("Problem creating feed",e);
    }

    result
  }

  def feed() {
    log.debug("SourcefeedController::feed ${params.id}");
    def result = [:]
    result.feed = SourceFeed.findByUriname(params.id)

    def entries_base_qry = 'from Entry as e where e.ownerFeed.uriname = :owner'

    result.totalEntries = Entry.executeQuery('select count(e) '+entries_base_qry,[owner:params.id])[0]
    result.latestEntries = Entry.executeQuery('select e '+entries_base_qry+' order by entryTs desc',[owner:params.id],[max:50])
    result
  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def toggleSourceEnabled() {
    def result = [:]
    log.debug("SourcefeedController::feed ${params.id}");
    SourceFeed.withTransaction {
      def feed = SourceFeed.findByUriname(params.id)
      feed.enabled = !feed.enabled
      feed.save(flush:true, failOnError:true);
    }
    request.getHeader('referer')
    def referer = request.getHeader('referer')
  
    redirect(url: referer)
  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def releaseBlockedFeeds() {
    try {
      SourceFeed.withTransaction {
        SourceFeed.executeUpdate('update SourceFeed sf set sf.status=:paused where sf.status=:inProcess and sf.lastStarted < :mtpAgo',
                                 [inProcess:'in-process', paused:'paused', mtpAgo:System.currentTimeMillis()-MAX_TIME_FOR_PROCESSING])
      }
    }
    catch ( Exception e ) {
      log.warn("problem trying to release blocked feeds",e);
    }
    def referer = request.getHeader('referer')
    redirect(url: referer)

  }
  
}

service/grails-app/views/sourcefeed/feed.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Source Feed : .....</title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="container-fluid">
        <h1>[${feed.id}] <a href="${feed.baseUrl}">${feed.uriname} / ${feed.name}</a></h1>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Feed Info</h3>
          </div>
          <div class="panel-body form-horizontal">
            <div class="form-group">
              <label class="col-sm-2 control-label">URL</label>
              <div class="col-sm-10"><p class="form-control-static">${feed.baseUrl}</p></div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Semantic Status</label>
              <div class="col-sm-10"><p class="form-control-static"><strong>${feed.capAlertFeedStatus}</strong> (operating|testing|OTHER) - only operating and testing feeds will be harvested</p></div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Harvester Control Status</label>
              <div class="col-sm-10"><p class="form-control-static"><strong>${feed.status}</strong> (in-process|paused)</p></div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Last fetch status</label>
              <div class="col-sm-10"><p class="form-control-static"><strong>${feed.feedStatus}</strong>(Last completed=<g:formatDate date="${new Date(feed.lastCompleted)}"/>, highest timestamp=<g:formatDate date="${new Date(feed.highestTimestamp?:0)}"/>)</p></div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Health Last Hour</label>
              <div class="col-sm-10"><p backgroundColor="" class="form-control-static">
                ${feed.latestHealth}%
              </p></div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Last Error (If any)</label>
              <div class="col-sm-10"><p class="form-control-static"><strong>${feed.lastError}</strong></p></div>
            </div>
          </div>
        </div>


        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Feed Activity - last 24 hours</h3>
          </div>
          <div class="panel-body form-horizontal">
            <g:set var="stats" value="${feed.getHistogramLastDay()}"/>
            <table class="table">
              <thead>
                <tr>
                  <th class="col-md-1">Hour (UTC)&nbsp;</th>
                  <g:each in="${stats}" var="h">
                    <th>${h.hour}</th>
                  </g:each>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Error Count &nbsp;</th>
                  <g:each in="${stats}" var="h">
                    <td>${h.errorCount}</td>
                  </g:each>
                </tr>
                <tr>
                  <th>Success Count &nbsp;</th>
                  <g:each in="${stats}" var="h">
                    <td>${h.successCount}</td>
                  </g:each>
                </tr>
                <tr>
                  <th>New Entries</th>
                  <g:each in="${stats}" var="h">
                    <td>${h.newEntryCount}</td>
                  </g:each>
                </tr>
                <tr>
                  <th>Health</th>
                  <g:each in="${stats}" var="h">
                    <td>
                      ${h.health}%
                    </td>
                  </g:each>
                </tr>
              </tbody>
            </table>
          </div>
        </div>


        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Recent Issues</h3>
          </div>
          <div class="panel-body form-horizontal">
            <g:set var="latest_issues" value="${feed.latestIssues(5)}"/>
            <g:if test="${latest_issues.size() > 0 }">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Key</th>
                    <th>Message</th>
                    <th>First Seen</th>
                    <th>Last Seen</th>
                    <th>Repeated</th>
                  </tr>
                </thead>
                <tbody>
                  <g:each in="${latest_issues}" var="li">
                    <tr>
                      <td>${li.key} </td>
                      <td>${li.message} </td>
                      <td><g:formatDate date="${new Date(li.firstSeen)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                      <td><g:formatDate date="${new Date(li.lastSeen)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                      <td>${li.occurrences} </td>
                    </tr>
                  </g:each>
                </tbody>
              </table>
            </g:if>
            <g:set var="feed_flags" value="${feed.getFlags()}"/>
            <g:if test="${feed_flags.size() > 0 }">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Flag</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>First Seen</th>
                    <th>Last Seen</th>
                    <th>Expiry</th>
                  </tr>
                </thead>
                <tbody>
                  <g:each in="${feed_flags}" var="flag">
                    <tr>
                      <td>${flag.definition.code} </td>
                      <td>${flag.definition.name} </td>
                      <td>${flag.definition.type} </td>
                      <td><g:formatDate date="${new Date(flag.firstSeen)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                      <td><g:formatDate date="${new Date(flag.lastSeen)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                      <td>
                        <g:formatDate date="${new Date(flag.expiryTime)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/>
                        ( ${flag.expiryTime - System.currentTimeMillis()} ) 
                      </td>
                    </tr>
                    <tr>
                      <td colspan="6">${flag.definition.advice}</td>
                    </tr>
                  </g:each>
                </tbody>
              </table>
            </g:if>
          </div>
        </div>


        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Recent Entries</h3>
          </div>
          <div class="panel-body form-horizontal">

            <table class="table table-striped well">
              <thead>
                <tr>
                  <th>Timestamp</th>
                  <th>Entry</th>
                </tr>
              </thead>
              <tbody>
                <g:each in="${latestEntries}" var="f" >
                  <tr>
                    <td><g:formatDate date="${new java.util.Date(f?.entryTs)}" format="yyyy-MM-dd'T'HH:mm:ss.SSS" /></td>
                    <td>
                      <strong><a href="${f.link}">${f.title}</a></strong>
                      <p>${f.description}</p>
                      <div class="container-fluid">
                        <div class="row">
                          <div class="col-md-6">
                            ${f.entry}
                          </div>
                          <div class="col-md-6">
                            ${f.entryAsJson}
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                </g:each>
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

service/grails-app/views/sourcefeed/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Registered Source Feeds</title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="container" style="vertical-align: middle; text-align:center;">

        <h1>Registered Feeds (${totalFeeds} found)</h1>
        <g:set var="UTCZONE" value="${TimeZone.getTimeZone('Z')}"/>
        <g:set var="curime" value="${new Date()}"/>
        As at: <g:formatDate format="yyyy-MM-dd'T'HH:mm:ssz" date="${curime}" timeZone="${UTCZONE}"/> (UTC) /
        <g:formatDate format="yyyy-MM-dd'T'HH:mm:ssz" date="${curime}"/> (Server)
        
        <g:if test="${(blocked_feeds?:0) > 0}">
          <h3>Warning: there are currently ${blocked_feeds} feeds in-process for longer than expected.
            <sec:ifLoggedIn>You can <g:link action="releaseBlockedFeeds">Release Manually</g:link></sec:ifLoggedIn>
          </h3>
        </g:if>

        <g:form controller="sourcefeed" action="index" method="get" class="form">
          <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Text input" value="${params.q}">
              <span class="input-group-addon"><input type="checkbox" name="filterHasErrors" value="on" ${params.filterHasErrors=='on'?'checked':''}> Has Errors</span>
              <span class="input-group-addon"><input type="checkbox" name="filterEnabled" value="on" ${params.filterEnabled=='on'?'checked':''}> Enabled</span>
              <span class="input-group-addon"><input type="checkbox" name="filterInProcess" value="on" ${params.filterInProcess=='on'?'checked':''}> In Process</span>
              <span class="input-group-btn"><button type="submit" class="btn btn-primary">Search</button></span>
              <input type="hidden" name="max" value="${params.max}"/>
          </div>
        </g:form>

        <div class="pagination">
          <g:paginate controller="sourcefeed" action="index" total="${totalFeeds}" next="Next" 
                      prev="Previous" omitNext="false" omitPrev="false" 
                      params="${params}"
                      />
        </div>

      </div>
    </div>
    <div class="row">
      <div class="container-fluid">
      
        <g:each in="${feeds}" var="f" >
          <div class="card">
            <div class="card-header">
              <h3><a href="${f.baseUrl}">${f.baseUrl}</a> (<g:link controller="sourcefeed" action="feed" id="${f.uriname}">${f.uriname}</g:link>)</h3>
            </div>
            <div class="card-body">
              <table class="table table-striped well">
                <thead>
                  <tr>
                    <th>Enabled</th>
                    <th>Status/Health</th>
                    <th>Topics</th>
                    <th>Tags</th>
                    <th>Fetcher Status</th>
                    <th>CAP Status</th>
                    <th>Last Completed</th>
                    <th>Poll Interval</th>
                    <th>Next Due</th>
                    <th>HTTP Last Modified</th>
                    <th>HTTP Expires</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      ${f.enabled?'Yes':'No'}
                      <sec:ifAllGranted roles='ROLE_ADMIN'>
                        <br/><g:link controller="sourcefeed" action="toggleSourceEnabled" id="${f.uriname}">toggle</g:link>
                      </sec:ifAllGranted>
                    </td>
                    <td>
                      <g:if test="${f.feedStatus=='ERROR'}">
                        <div class="alert alert-danger" role="alert">
                          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                          <span class="sr-only">Error</span>
                        </div>
                      </g:if>
                      <g:if test="${f.feedStatus=='OK'}">
                        <div class="alert alert-success" role="alert">
                          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                          <span class="sr-only">OK</span>
                        </div>
                      </g:if>
                      <g:if test="${f.feedStatus!='OK' && f.feedStatus!='ERROR'}">
                        ${f.feedStatus?:'Unset'}
                      </g:if>
                      <g:if test="${f.latestHealth}">
                        health:${f.latestHealth}
                      </g:if>
                    </td>
                    <td><ul><g:each in="${f.topics}" var="topic"><li>${topic.topic.name}</li></g:each></ul></td>
                    <td><ul><g:each in="${f.tags}" var="tv"><li>${tv.tag.tag}: <strong>${tv.value}</strong></li></g:each></ul></td>
                    <td>
                      ${f.status}
                      <g:if test="${f.status=='in-process'}">
                        <br/>started: <br/><g:formatDate date="${new Date(f.lastStarted)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/>
                        <br/>elapsed: <br/>${System.currentTimeMillis() - f.lastStarted}
                      </g:if>
                    </td>
                    <td>${f.capAlertFeedStatus}</td>
                    <td><g:formatDate date="${new Date(f.lastCompleted)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                    <td>${f.pollInterval}</td>
                    <td> 
                      <g:formatDate date="${new Date(f.nextPollTime)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/>
                    </td>
                    <td>${f.httpLastModified}</td>
                    <td>${f.httpExpires}</td>
                  </tr>

                  <sec:ifLoggedIn>
                    <g:set var="latest_issues" value="${f.latestIssues(5)}"/>
                    <tr>
                      <g:if test="${latest_issues.size() > 0 }">
                        <td colspan="12">
                          <table class="table table-striped">
                            <thead>
                              <tr> 
                                <th>Key</th>
                                <th>Message</th>
                                <th>First Seen</th>
                                <th>Last Seen</th>
                                <th>Repeated</th>
                              </tr>
                            </thead>
                            <tbody>
                              <g:each in="${latest_issues}" var="li">
                                <tr>
                                  <td>${li.key} </td>
                                  <td>${li.message} </td>
                                  <td><g:formatDate date="${new Date(li.firstSeen)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                                  <td><g:formatDate date="${new Date(li.lastSeen)}" format="yyyy-MM-dd HH:mm:ssz" timeZone="${UTCZONE}"/></td>
                                  <td>${li.occurrences} </td>
                                </tr>
                              </g:each>
                            </tbody>
                          </table>
                        </td>
                      </g:if>
                    </tr>
                  </sec:ifLoggedIn>
                  <tr>
                    <td colspan="12">
                      <g:set var="stats" value="${f.getHistogramLastDay()}"/>
                      <table class="table">
                        <thead>
                          <tr>
                            <th class="col-md-1">Hour (UTC)&nbsp;</th>
                            <g:each in="${stats}" var="h">
                              <th>${h.hour}</th>
                            </g:each>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                           <th>Error Count &nbsp;</th>
                            <g:each in="${stats}" var="h">
                              <td>${h.errorCount}</td>
                            </g:each>
                          </tr>
                          <tr>
                           <th>Success Count &nbsp;</th>
                            <g:each in="${stats}" var="h">
                              <td>${h.successCount}</td>
                            </g:each>
                          </tr>
                          <tr>
                           <th>New Entries</th>
                            <g:each in="${stats}" var="h">
                              <td>${h.newEntryCount}</td>
                            </g:each>
                          </tr>
                          <tr>
                           <th>Health</th>
                            <g:each in="${stats}" var="h">
                              <td>${h.health}</td>
                            </g:each>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </g:each>
    
        <g:link class="btn" action="registerFeed">Register New Feed</g:link>
  
      </div>
    </div>
  </div>
</body>
</html>